examples/react/package.json, examples/react/src/components/Home.tsx, examples/react/src/components/Interview.tsx, examples/react/src/components/Screener.tsx, examples/react/src/wizards/exampleInterview.ts, examples/react/src/wizards/exampleScreener.ts, examples/react/src/wizards/exampleScreenerSerialized.ts, examples/react/src/wizards/wizardMap.ts, examples/react/src/wizards/wizardSerializations.ts, examples/react/yarn.lock
WIP support json-logic throughout the wizard writing experience
=> json-logic examples in content node text, conditionals, loops

examples/react-spellbook/package.json, examples/react-spellbook/yarn.lock, package.json, packages/spellbook/package.json, packages/spellbook/src/components/contentNodes/ContentNodeEditor.tsx, packages/spellbook/src/components/contentNodes/consts.ts, packages/wizards-of-react/package.json, packages/wizards-of-react/src/components/ContentNode.tsx
JSON Array content node editor + tweak to move the array limit option to the config obj + allow some options/fields on content node editors to been hidden (ex: assign/reorder for json array schema content node editors)
=> JsonArray Content Node Editor

examples/react-spellbook/package.json, examples/react-spellbook/yarn.lock, packages/spellbook/package.json, packages/spellbook/src/SpellBook.tsx, packages/spellbook/src/components/logic/JsonLogicBuilder.tsx
Swapped out the json-logic filter for some lodash functions that'll be simpler w/ var references. Also added some CSS to hide scroll bars
=> JSON Logic Filters

examples/react-wizards/package.json, examples/react-wizards/src/spells/exampleSpawnedMachine.ts, examples/react-wizards/src/wizards/wizardModelMap.ts, examples/react-wizards/yarn.lock, packages/spellbook/package.json, packages/spells/package.json, packages/spells/src/machines/functions/templateFunctionToValue.ts, packages/wizards-of-react/package.json, packages/wizards-of-react/src/components/WizardStateViewer.tsx
Added an input that targets a property on a resource's nested object. Did this in the process of trying to debug another issue for Upsolve and realized an odd behavior with the acorn parser, which would break/hang in my browser with `ecmaVersion: "latest"`. Changed it to be fixed at `ecmaVersion: 2020` since we're just parsing JSON and don't need advanced features/syntax.
=> Example Input for Nested Obj

packages/spellbook/package.json, packages/wizards-of-react/package.json, packages/wizards-of-react/src/components/WizardStateViewer.tsx, packages/wizards-of-react/src/components/wizardLayout/WizardNavigationPanel.tsx
=> Remove Legacy Journey exitTo

packages/spellbook/package.json, packages/wizards-of-react/package.json, packages/wizards-of-react/src/components/ContentNode.tsx
title > headerTitle & svg > headerIconSVG props
=> Collapsible Panel Prop Change

packages/wizards-of-react/package.json, packages/wizards-of-react/src/components/ContentNode.tsx
Wanted a way to have the default value of a select drop down be more context specific
=> defaultOptionText for Select Content Nodes

examples/react-wizards/package.json, examples/react-wizards/src/spells/exampleInterview.ts, examples/react-wizards/src/spells/exampleScreener.ts, examples/react-wizards/src/spells/exampleSpawnedMachine.ts, examples/react-wizards/yarn.lock, packages/wizards-of-react/package.json, packages/wizards-of-react/src/components/ContentNode.tsx
Allow enabling an attention text field and unit dropdown on address inputs. Also allow overrides labels
=> Address Attention, Unit, Configs

examples/react-wizards/src/spells/exampleInterview.ts, packages/wizards-of-react/package.json, packages/wizards-of-react/src/components/ContentNode.tsx
For extremely long options lists, such as selecting multiple nationalities, the multi-select with checkboxes isn't feasible. So this provides an alternate style where you use a select drop down
=> MultiSelect List

examples/react-wizards/src/spells/exampleInterview.ts, packages/spells/package.json, packages/spells/src/validation/baseValidations.ts, packages/wizards-of-react/package.json, packages/wizards-of-react/src/components/ContentNode.tsx, packages/wizards-of-react/src/components/contentNodes/InputPhoneNumber.tsx
If a person starts entering a phone number that can't be valid, have the input onChange pass back a null so we don't propagate out bad phone numbers
=> InputPhoneNumber null

packages/wizards-of-react/package.json, packages/wizards-of-react/src/components/ContentNode.tsx
Needed to refine our multi-select options with spacing, clearing the select statement, fix the X icon
=> MultiSelect Options

packages/wizards-of-react/package.json, packages/wizards-of-react/src/components/contentNodes/InputPhoneNumber.tsx
Passing props through for E2E selectors
=> InputPhoneNumber data-test-id/label

examples/react-wizards/package.json, examples/react-wizards/src/spells/exampleInterview.ts, examples/react-wizards/yarn.lock, packages/wizards-of-react/src/components/ContentNode.tsx
disable the button when the validation fails.
update the example with a bug case, details in a comment in react-wizards example
=> ContentNode Buttons Disabled when Invalid

examples/react-wizards/src/spells/exampleInterview.ts, packages/wizards-of-react/package.json, packages/wizards-of-react/src/components/ContentNode.tsx
earlier push disabled all buttons when there was invalid input on the page, now we only disable the submit buttons
=> Only disable submit buttons

packages/wizards-of-react/package.json, packages/wizards-of-react/src/components/ContentNode.tsx
added asignConfig and asignValue to the ASSIGN_CONTEXT event, so we can react to data changes from input
=> improvement: added more info to ASSIGN_CONTEXT event

examples/react-wizards-i18n/src/components/Home.tsx, packages/spellbook/src/placeholders/SpellbookWizardWrap.tsx, packages/spells/package.json, packages/spells/src/constants/contentNodeTemplates.tsx, packages/spells/src/types.ts, packages/wizards-of-react/src/components/wizardLayout/WizardNavigationPanel.tsx
to allow for translating the back button copy lol
=> improvement: remove back button css and misc

packages/wizards-of-react/package.json, packages/wizards-of-react/src/components/WizardStateMachineManager.tsx
need to drill the translate function recursively
=> fix: fix recursive machine translations

packages/spellbook/package.json, packages/spells/package.json, packages/wizards-of-react/package.json, packages/wizards-of-react/src/components/contentNodes/InputPhoneNumber.tsx, yarn.lock
Was getting a `manypkg check` error: `@xstate-wizards/wizards-of-react has a dependency on react-player@^2.10.1 but the highest range in the repo is ^2.11.0, the range should be set to ^2.11.0` amongst others when doing a yarn install from the root of the mono-repo, so just needed to bump things
=> Dependencies Sync

packages/wizards-of-react/package.json, packages/wizards-of-react/src/components/ContentNode.tsx
Radio selects didn't have the by line addition. Added!
=> Radio Bylines

packages/wizards-of-react/package.json, packages/wizards-of-react/src/index.ts
Need to do multiple variations of a state machine test, so I want to use the puppeteer utils functions w/o running within the test plan function.
=> Wizard Puppeteer Utils Accessible

packages/wizards-of-react/package.json, packages/wizards-of-react/src/testing/wizardPuppeteerUtils.ts
Lots of typing errs using the wizard util
=> Typings for tapInput

README.md, packages/wizards-of-svelt/README.md, packages/wizards-of-svelte/README.md
Hey there! Thanks for the great library, love what's going on here. Still getting into it (I'm evaluating it for a Svelte project), but I spotted a few copyedits and figured a quick PR wouldn't hurt. :)
By the by, I've got a short list of questions I've been accumulating as I come up to speed. For those, would an Issue, Discussion, Discord, or email be best?
=> A few copyedits around Svelte, and other minor readme changes
